Parameters:
  AWSAccountName:
    Description: "Defining the name of the account"
    Type: String
 
Resources:
  # Archival files S3 bucket for WIS-Archive solutions.
  WisArchiveArchivalBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "sandip-archival"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  
  # IAM role for Archive and Retrieve Lambda with require permission for WIS-Archive solutions.
  WisArchiveLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "{{ application_name }}-{{tibco_env_name}}-app-S3FullAccess-LambdaRole"
      AssumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"lambda.amazonaws.com"},"Action":"sts:AssumeRole"}]}'
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"
        - "arn:aws:iam::aws:policy/AmazonElasticFileSystemClientFullAccess"
 
  # Archival lambda for files processing for WIS-Archive solutions.
  WisArchiveArchivalLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: "This lambda is responsible for archieving the source files as a part of wis archival."
      Environment:
        Variables:
          batchSize: "{{ batchSize }}"
      FunctionName: !Sub "{{ application_name }}-{{ tibco_env_name }}-ArchivalLambda"
      Handler: "com.nabwis.archival.App::handleRequest"
      Code:
        S3Bucket: !Sub "hellotrupti"
        S3Key: "lambda/hello-lambda.jar"
      MemorySize: {{ MemorySize }}
      Role: !GetAtt WisArchiveLambdaRole.Arn
      Runtime: "java8"
      Timeout: {{ Timeout }}
      TracingConfig:
        Mode: "PassThrough"
      
Outputs:
  StackName:
    Description: The wis-archive solution cloud formation stack name
    Value: !Sub "${AWS::StackName}"
  S3ArchivalBucket:
    Value: !Ref WisArchiveArchivalBucket
    Description: Name of the wis-archive solution Archival S3 bucket.
  ArchivalLambdaArchiveSolution:
    Value: !Ref WisArchiveArchivalLambda
    Description: Name of the wis-archive solution Archival Lambda.
